CREATE OR REPLACE TABLE DIM_COUNTRY AS SELECT
    ROW_NUMBER() OVER (ORDER BY REFERENCE_AREA_CODE) as country_id,
    REFERENCE_AREA_CODE as country_code,
    REFERENCE_AREA_DESCRIPTION as country_name
FROM (SELECT DISTINCT REFERENCE_AREA_CODE, REFERENCE_AREA_DESCRIPTION FROM MIGRATION_STAGING);

CREATE OR REPLACE TABLE DIM_ORIGIN AS SELECT 
    ROW_NUMBER() OVER (ORDER BY PLACE_OF_BIRTH_CODE) as iddim_origin,
    PLACE_OF_BIRTH_CODE as origin_code,
    PLACE_OF_BIRTH_DESCRIPTION as origin_name
FROM (SELECT DISTINCT PLACE_OF_BIRTH_CODE, PLACE_OF_BIRTH_DESCRIPTION FROM MIGRATION_STAGING);

create or replace TABLE DIM_TIME as SELECT 
ROW_NUMBER() OVER (ORDER BY TIME_PERIOD) as time_id,
CAST(TIME_PERIOD as INTEGER) as year
FROM (SELECT DISTINCT TIME_PERIOD from MIGRATION_STAGING);

create or replace TABLE DIM_DEMOGRAPHICS AS SELECT
ROW_NUMBER() OVER (ORDER BY SEX_CODE, CITIZENSHIP_CODE) AS iddim_demographics,
SEX_CODE,
SEX_DESCRIPTION as gender,
CITIZENSHIP_CODE,
CITIZENSHIP_DESCRIPTION as citizenship from (select DISTINCT SEX_CODE, SEX_DESCRIPTION, CITIZENSHIP_CODE, CITIZENSHIP_DESCRIPTION FROM MIGRATION_STAGING);

create or replace TABLE DIM_FLOW AS SELECT 
ROW_NUMBER() OVER (ORDER BY MEASURE_CODE) as flow_id,
MEASURE_CODE AS measure_code,
MEASURE_DESCRIPTION as measure_desc FROM (SELECT DISTINCT MEASURE_CODE, MEASURE_DESCRIPTION FROM MIGRATION_STAGING);

CREATE OR REPLACE TABLE FACT_MIGRATION AS SELECT
ROW_NUMBER() OVER (order by MIGRATION_STAGING.TIME_PERIOD) as migration_id, DIM_COUNTRY.country_id, DIM_ORIGIN.IDDIM_ORIGIN, DIM_TIME.time_id, DIM_DEMOGRAPHICS.IDDIM_DEMOGRAPHICS, DIM_FLOW.flow_id,CAST(MIGRATION_STAGING.OBSERVATION_VALUE AS int) as migrant_count,

LAG(CAST(migration_staging.OBSERVATION_VALUE AS INT)) OVER (PARTITION BY DIM_COUNTRY.country_id, DIM_ORIGIN.IDDIM_ORIGIN, DIM_DEMOGRAPHICS.IDDIM_DEMOGRAPHICS, DIM_FLOW.flow_id ORDER BY DIM_TIME.year) as prev_year_count
FROM MIGRATION_STAGING 

JOIN DIM_COUNTRY ON MIGRATION_STAGING.REFERENCE_AREA_CODE = DIM_COUNTRY.country_code
JOIN DIM_ORIGIN ON MIGRATION_STAGING.PLACE_OF_BIRTH_CODE = DIM_ORIGIN.ORIGIN_CODE
JOIN DIM_TIME ON CAST(MIGRATION_STAGING.TIME_PERIOD AS INTEGER) = DIM_TIME.YEAR
join DIM_DEMOGRAPHICS ON MIGRATION_STAGING.SEX_CODE = DIM_DEMOGRAPHICS.SEX_CODE AND MIGRATION_STAGING.CITIZENSHIP_CODE = DIM_DEMOGRAPHICS.CITIZENSHIP_CODE
JOIN DIM_FLOW ON MIGRATION_STAGING.MEASURE_CODE = DIM_FLOW.MEASURE_CODE;
